### ISSUE TITLE
Support web workers

### ISSUE THREAD

**Issue by joaovieira** [mo/abortcontroller-polyfill#11]
While working on https://github.com/github/fetch/pull/592 and bringing this in to have a full-featured polyfill for testing, I noticed it doesn't work inside a web worker as it uses the `dom` to create an `EventTarget`. Would you be willing to rework the `Emitter` class to support that?

<img width="450" alt="screen shot 2018-02-02 at 01 16 20" src="https://user-images.githubusercontent.com/474603/35711823-d9747de6-07b6-11e8-9498-a01d145555cf.png">

**Comment by getify** [comment]
I've had to hack this polyfill to be able to run it in node... would be very helpful if this browser/DOM dependency could be refactored out. :)

**Comment by joaovieira** [comment]
I've also ended up having to implement an `EventTarget` [here](https://github.com/jmeas/fetch/pull/2/files) so I'm bringing that over.

Also noticed this polyfill doesn't use the`AbortSignal.onabort` handler defined in the spec.
