### ISSUE TITLE
Remove reference to babel preset "latest"

### ISSUE THREAD

**Issue by dysonpro** [mo/abortcontroller-polyfill#18]
When I try to bundle this polyfill in my application I get the following error:

`Error: Couldn't find preset "latest" relative to directory ".../node_modules/abortcontroller-polyfill"`

Babel preset `latest` is deprecated and this project references `babel-preset-env`

No error occurs if I change it to `"env"` or remove the babel presets entry altogether.

Can the babel presets entry in `package.json` be changed to `"env"` or else removed  (due to use of the `.babelrc` file)?
``` son
"babel": {
    "presets": [
      "latest"   <-- change to "env"
    ]
  },
```

**Comment by mo** [comment]
Fixed and released as v1.1.5
