### ISSUE TITLE
Make compatible with Node.js

### ISSUE THREAD

**Issue by TimothyGu** [mo/abortcontroller-polyfill#2]
Hi, we are interested in using this module in [node-fetch](https://github.com/bitinn/node-fetch) (basically a `fetch()` for Node.js), but it seems like this module does not yet support Node.js. Would you folks be opposed to a Node.js version using something like [event-target-shim](https://www.npmjs.com/package/event-target-shim) or Node.js' internal `EventEmitter` class that makes this package Node.js-compatible? Thanks!

**Comment by mo** [comment]
I'd be happy to merge such a patch

**Comment by jimmywarting** [comment]
If we go down this road, should we remove the part where you patch the fetch?
I think this should only be about having a clean and simple Abortable Controller and have nothing to do with fetch as it's node-fetch's job to abort the request

> This "polyfill" doesn't actually close the connection when the request is aborted, but it calls .catch() with err.name == 'AbortError' instead of .then().

Otherwise it will still make the request...

**Comment by mo** [comment]
@jimmywarting it sounds to me like the cleanest solution is what you suggested in the node-fetch issue, i.e. that you break out the AbortController itself into an "abortcontroller" npm package and that node-fetch depends on that while also adding support for the "signal" property directly in node-fetch itself.

**Comment by Haroenv** [comment]
I'd like a pure Abortcontroller polyfill for node and browser too!

**Comment by jimmywarting** [comment]
I broke out fetch into a separate file in a pull request #6

**Comment by mo** [comment]
pushed to master now

**Comment by caub** [comment]
I still get `Cannot read property 'AbortController' of undefined error` with version 1.1.2 when doing `require('abortcontroller-polyfill')`

**Comment by mo** [comment]
Just wanted to note that @caub just landed a PR that makes it very easy to use the abortcontroller-polyfill in node.js ... have a look at the updated READMD.md
