### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined at __webpack_require__

### ISSUE THREAD

**Issue by Jorybraun** [mo/abortcontroller-polyfill#31]
After adding the polyfil to the top of the entry point in the webpack throws an error on initial load. 

 "webpack": "^4.20.2",
  "abortcontroller-polyfill": "^1.2.3",

**Comment by mo** [comment]
* What's the error?
* Which browser are you using?
* Do you have sample project or URL where the bug can be reproduced?

**Comment by Jorybraun** [comment]
This seemed to be related to webpack/npm
