### ISSUE TITLE
ReferenceError: DOMException is not defined in node

### ISSUE THREAD

**Issue by skurgansky-sugarcrm** [mo/abortcontroller-polyfill#45]
Exception has occurred: ReferenceError
ReferenceError: DOMException is not defined
    at _fetch (/node_modules/abortcontroller-polyfill/dist/cjs-ponyfill.js:400:9)

**Comment by mo** [comment]
What are the steps to reproduce this issue? What browser did you use? Which URL did you load etc?

**Comment by skurgansky-sugarcrm** [comment]
this issue is related to use case with node. I found out later that node doesn't support AbortController but believed in this lib because in readme it has node installation.
https://github.com/mo/abortcontroller-polyfill#using-it-on-nodejs

But it doesn't work at all.

**Comment by jimmywarting** [comment]
DOMException exist globally in NodeJS v17 doe it's supported as early as in v10.5 
but not easily accessible without [node-domexception](https://github.com/jimmywarting/node-domexception)

AbortController came into NodeJS v15
