### ISSUE TITLE
Request is never closed on server side (node-fetch@2.6.0 + abortcontroller-polyfill@1.4.0)

### ISSUE THREAD

**Issue by majo44** [mo/abortcontroller-polyfill#47]
Simple sample code:
```
// Server implmentation
import express from 'express';
const app = express();
app.use((req, res, next) => {
   req.on('close', () => console.log('CLOSED'));
   next();
});
app.get('*', (req, res) => setTimeout(() => res.send('Ok'), 5000));
app.listen(808, () => console.log('http://localhost:808'));
```
```
// Client  code
let execute = async (fetch, AbortController) => {
    const ac = new AbortController();
    const rP = fetch('http://localhost:808', { signal: ac.signal });
    setTimeout(() => ac.abort(),1000);
    try {
        console.log(await rP);
    } catch (ex) {
        console.log(ex.name);
    }
};
```
When I run client code on browser:
```
   execute(fetch, AbortController)
```
On server console I see the 'CLOSED' on client 'AbortErrror'.

Now when I try to run client on node :
```
import { AbortController, AbortSignal, abortableFetch } from 'abortcontroller-polyfill/dist/cjs-ponyfill';
import nodeFetch from 'node-fetch';
const { fetch } = abortableFetch(nodeFetch);
execute(fetch, AbortController);
```
On client I see 'AbortErrror', but there is no any log on Server .

For compassion,  if I use https://www.npmjs.com/package/abort-controller : 
```
import AbortController from 'abort-controller';
import fetch from 'node-fetch';
execute(fetch, AbortController);
```
I have same result as on browser.

I lost half a day to finally find that 'abortcontroller-polyfill' is not support real request cancellation (I was looking for problem in my code :(). 
Maybe this is problem with this particular versions, I do not know.
Please fix that or at least add information about such limitation in documentation.  
Best regards.

**Comment by getify** [comment]
If the underlying `fetch(..)` (and network layer) doesn't support cancellation from abort controllers on a certain platform (like node, or an older browser), then it's only ever going to be a shallow cancellation, not a true full cancellation. Not much a polyfill could do to fix that.

**Comment by majo44** [comment]
@getify 
Did you correctly read issue description?
There is compassion of 3 cases (it is real code, so you can run it by self) where each is runs on the same network (layer), same server implementation, same node version.  One is using native browser `fetch`, and two others are using same version of `node-fetch` implementation, but different implementation of AbortController polyfill, the difference is only that. Only the code which is using `abortcontroller-polyfill` is not behave as expected. So I think the problem is not in `fetch` implementation (and network layer) but  in implementation of polyfill, as other implementation of polyfill behave properly.  As I see in the readme of this library that it should work with node.js I think it is real issue that is not working in this environment as expected.

**Comment by mo** [comment]
@majo44 it says at the very top that it doesn't actually cancel:

![image](https://user-images.githubusercontent.com/7117/83011417-1d562480-a01a-11ea-8589-ba9af19dbdae.png)

As getify points out, it's not possible to _actually_ cancel the fetch request. What you can do, is to replace the entire fetch() function with a polyfill that calls into XmlHttpRequest (which does support cancellation), but this would be a much much bigger polyfill so it makes no sense to add that into this polyfill. Instead, maybe that could be added to some fetch polyfill like https://github.com/github/fetch The purpose of abortcontroller-polyfill is to make sure that the code still runs in older browsers.

**Comment by majo44** [comment]
@mo thanks for clarification. 
Sorry I missed info about missing real request cancelation at is on header not in node.js section. On other hand I believe that on node.js (node-fetch) it is very easy to add support for the real request cancelation as node-fetch is supports it by self (https://github.com/node-fetch/node-fetch/pull/539) but just not providing AbortController and AbortSignal constructors  (that is why https://www.npmjs.com/package/abort-controller is required ). 

As I building isomorphic solution, I will use node-fetch + abort-controller on node and whatwg-fetch +  abortcontroller-polyfill on legacy browsers. So I will have real cancelation available everywhere where it is possible. One additional dependency, but I can live with that.
