### ISSUE TITLE
Support throwIfAborted()

### ISSUE THREAD

**Issue by onestep** [mo/abortcontroller-polyfill#70]
There is a modern API method to throw abort reason, if operation was aborted: `AbortSignal.throwIfAborted()`.

**WhatWG specification:** https://dom.spec.whatwg.org/#ref-for-dom-abortsignal-throwifaborted

**Example implementation:** nodejs/node#40951

If would be great if this polyfill will support it.

**Comment by mo** [comment]
available in 1.7.6
